- name: Install openldap packages
  yum:
   name: "{{ packages }}"
   state: latest

- name: add client to ldap with command
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ server_host }}.{{ dc1 }}.{{ dc2 }} --ldapbasedn="dc={{ dc1 }},dc={{ dc2 }}" --enablemkhomedir --update
